{% set name = "yandexcloud" %}
{% set version = "0.350.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/yandexcloud-{{ version }}.tar.gz
  sha256: 105dcd2820b93497022f36081b1807c47a8764c929c40ec86c6c01f1431cabe5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.2,<76.1.0
  run:
    - python >={{ python_min }}
    - cryptography >=44.0.0
    - grpcio >=1.68.1,<2
    - protobuf >=5.29.1,<6
    - googleapis-common-protos >=1.66.0,<2
    - pyjwt >=2.10.1,<3
    - requests >=2.32.3,<3
    - six >=1.17.0,<2
    - grpcio-tools >=1.68.1
    - deprecated >=1.2.18

test:
  imports:
    - yandex
    - yandex.cloud
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/yandex-cloud/python-sdk
  summary: The Yandex.Cloud official SDK
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/yandex-cloud/python-sdk
  doc_url: https://github.com/yandex-cloud/python-sdk

extra:
  recipe-maintainers:
    - xylar
