{% set name = "yandexcloud" %}
{% set version = "0.328.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/yandexcloud-{{ version }}.tar.gz
  sha256: 1f30e1c98ddbb528c0422edb00575626d202372400231d9d63566c30381dba8d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - cryptography >=41.0.7,<43
    - grpcio >=1.64.0,<2
    - protobuf >=4.25.3,<5
    - googleapis-common-protos >=1.63.0,<2
    - pyjwt >=2.8.0,<3
    - requests >=2.32.3,<3
    - six >=1.16.0,<2

test:
  imports:
    - yandex
    - yandex.cloud
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/yandex-cloud/python-sdk
  summary: The Yandex.Cloud official SDK
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/yandex-cloud/python-sdk
  doc_url: https://github.com/yandex-cloud/python-sdk

extra:
  recipe-maintainers:
    - xylar
