{% set name = "yandexcloud" %}
{% set version = "0.331.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/yandexcloud-{{ version }}.tar.gz
  sha256: a724c8d5b696bdca7de3eb3c1f86cdf425da804b64144f47adc3faa1ab398631

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.2
  run:
    - python >={{ python_min }}
    - cryptography >=43.0.1
    - grpcio >=1.64.0,<2
    - protobuf >=5.0.0,<6
    - googleapis-common-protos >=1.63.0,<2
    - pyjwt >=2.8.0,<3
    - requests >=2.32.3,<3
    - six >=1.16.0,<2
    - grpcio-tools >=1.59.3

test:
  imports:
    - yandex
    - yandex.cloud
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/yandex-cloud/python-sdk
  summary: The Yandex.Cloud official SDK
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/yandex-cloud/python-sdk
  doc_url: https://github.com/yandex-cloud/python-sdk

extra:
  recipe-maintainers:
    - xylar
