{% set name = "yandexcloud" %}
{% set version = "0.329.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/yandexcloud-{{ version }}.tar.gz
  sha256: fb7a20095011d1c43fd16384a5e6df92686ff1ccc0a2f5ac40de986f1ffbf47d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - cryptography >=2.8
    - grpcio >=1.64.0
    - protobuf >=4.23.4
    - googleapis-common-protos >=1.63.0
    - pyjwt >=1.7.1
    - requests >=2.22.0
    - six >=1.14.0

test:
  imports:
    - yandex
    - yandex.cloud
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/yandex-cloud/python-sdk
  summary: The Yandex.Cloud official SDK
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/yandex-cloud/python-sdk
  doc_url: https://github.com/yandex-cloud/python-sdk

extra:
  recipe-maintainers:
    - xylar
