{% set name = "yandexcloud" %}
{% set version = "0.270.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/yandexcloud-{{ version }}.tar.gz
  sha256: 0865852d1248edd284419511eac7a415b4ec85137a740f45cd2d6173c4d51005

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    # avoid dependency on importlib-metadata and stay noarch: python
    - python >=3.8
    - cryptography >=2.8
    - grpcio >=1.56.2
    - protobuf >=4.23.4
    - googleapis-common-protos >=1.59.1
    - pyjwt >=1.7.1
    - requests >=2.22.0
    - six >=1.14.0

test:
  imports:
    - yandex
    - yandex.cloud
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yandex-cloud/python-sdk
  summary: The Yandex.Cloud official SDK
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/yandex-cloud/python-sdk
  doc_url: https://github.com/yandex-cloud/python-sdk

extra:
  recipe-maintainers:
    - xylar
